networks:
  testnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: chat_app_image
    container_name: chat_server
    command: ./build/release/server
    working_dir: /app
    tty: true
    stdin_open: true
    networks:
      testnet:
        ipv4_address: 172.28.0.10
    ports:
      - "4400:4400/tcp"
      - "4400:4400/udp"

  client:
    image: chat_app_image
    command: sleep 99999999
    working_dir: /app
    networks:
      - testnet
    depends_on:
      - server
    tty: true
    stdin_open: true
    deploy:
      replicas: 3